/// Generated by AssetsRefGenerator on 2020/07/02
class Res {
  static const String instant_weather_new = "images/instant_weather_new.png";
  static const String instant_weather_new_foreground =
      "images/instant_weather_new_foreground.png";
  static const String instant_weather_new_round =
      "images/instant_weather_new_round.png";
  static const String circle_blue_solid_background =
      "images/svg/circle_blue_solid_background.xml";
  static const String circle_orange_solid_background =
      "images/svg/circle_orange_solid_background.xml";
  static const String circle_orange_stroke_background =
      "images/svg/circle_orange_stroke_background.xml";
  static const String ic_arrow_left = "images/svg/ic_arrow_left.xml";
  static const String ic_arrow_right = "images/svg/ic_arrow_right.xml";
  static const String ic_cached = "images/svg/ic_cached.xml";
  static const String ic_close = "images/svg/ic_close.xml";
  static const String ic_format_list = "images/svg/ic_format_list.xml";
  static const String ic_home = "images/svg/ic_home.xml";
  static const String ic_humidity = "images/svg/ic_humidity.xml";
  static const String ic_insert_chart = "images/svg/ic_insert_chart.xml";
  static const String ic_instant_weather_foreground =
      "images/svg/ic_instant_weather_foreground.xml";
  static const String ic_palette = "images/svg/ic_palette.xml";
  static const String ic_pressure = "images/svg/ic_pressure.xml";
  static const String ic_search = "images/svg/ic_search.xml";
  static const String ic_settings = "images/svg/ic_settings.xml";
  static const String ic_wb_sunny_black_24dp =
      "images/svg/ic_wb_sunny_black_24dp.xml";
  static const String ic_wind = "images/svg/ic_wind.xml";
}
